In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
with open(f"../results/training_in_forces.npy", "rb") as f:
    training_in = np.load(f)

with open(f"../results/training_out_forces.npy", "rb") as f:
    training_out = np.load(f)

In [45]:
trainX = torch.tensor(training_in, dtype=torch.float32)
trainY = torch.tensor(training_out, dtype=torch.float32)

In [46]:
class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, layer_dim, output_dim):
        super(LSTMModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.layer_dim = layer_dim
        self.lstm = nn.LSTM(input_dim, hidden_dim, layer_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, h0=None, c0=None):
        # If hidden and cell states are not provided, initialize them as zeros
        if h0 is None or c0 is None:
            h0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
            c0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
        
        # Forward pass through LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])  # Selecting the last output
        return out, hn, cn

In [47]:
trainY.shape

torch.Size([6, 2000, 42])

In [48]:
# Initialize model, loss, and optimizer
model = LSTMModel(input_dim=42, hidden_dim=100, layer_dim=1, output_dim=42)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Training loop
num_epochs = 1000
h0, c0 = None, None  # Initialize hidden and cell states

for epoch in range(num_epochs):
    h0, c0 = None, None  # Initialize hidden and cell states
    for i in range(1, trainX.shape[1] + 1):
        model.train()
        optimizer.zero_grad()

        # Forward pass
        outputs, h0, c0 = model(trainX[:, i - 1:i, :], h0, c0)

        # Compute loss
        loss = criterion(outputs, trainY[:, i - 1, :])
        loss.backward()
        optimizer.step()

        # Detach hidden and cell states to prevent backpropagation through the entire sequence
        h0 = h0.detach()
        c0 = c0.detach()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [10/1000], Loss: 48684260.0000
Epoch [20/1000], Loss: 10455924.0000
Epoch [30/1000], Loss: 2093723.1250
Epoch [40/1000], Loss: 534974.0625
Epoch [50/1000], Loss: 277289.7500
Epoch [60/1000], Loss: 102973.0781
Epoch [70/1000], Loss: 27438.7012
Epoch [80/1000], Loss: 571940.0625
Epoch [90/1000], Loss: 9465.2227
Epoch [100/1000], Loss: 10075.1113
Epoch [110/1000], Loss: 44308.9375
Epoch [120/1000], Loss: 16573.2734
Epoch [130/1000], Loss: 25615.8535
Epoch [140/1000], Loss: 115573.4766
Epoch [150/1000], Loss: 1484.0935
Epoch [160/1000], Loss: 8382.4180
Epoch [170/1000], Loss: 42577.9141
Epoch [180/1000], Loss: 84487.8750
Epoch [190/1000], Loss: 77924.5859
Epoch [200/1000], Loss: 78889.5156
Epoch [210/1000], Loss: 32620.8359
Epoch [220/1000], Loss: 984304.0000
Epoch [230/1000], Loss: 157482.7969
Epoch [240/1000], Loss: 43075.0391
Epoch [250/1000], Loss: 93594.3516
Epoch [260/1000], Loss: 21306.2070
Epoch [270/1000], Loss: 116647.9062
Epoch [280/1000], Loss: 42917.4375
Epoch [290/1000]

KeyboardInterrupt: 

In [7]:
trainX[-2:-1, :400, :].shape

torch.Size([1, 400, 42])

In [27]:
predicted_400, h400, c400 = model(trainX[-1:, :400, :], None, None)

In [28]:
predicted_401, _, _ = model(trainX[-1:, 400:401, :], h400, c400)

In [29]:
predicted_401_comp, _, _ = model(trainX[-1:, :401, :], None, None)

In [38]:
predict_test = training_in[-1, 400, :]
predicted_test, _, _ = model(torch.tensor(predict_test[None, None, :], dtype=torch.float32), h400, c400)

In [39]:
predicted_400

tensor([[ 6.3041e-02, -1.7005e+02,  6.7185e-02, -1.6943e+02,  1.1316e-01,
         -1.6972e+02,  1.0122e-01, -1.6944e+02, -2.9860e-02, -1.7122e+02,
         -1.0494e-01, -1.6915e+02, -1.5843e-01, -1.7043e+02, -1.3934e-01,
         -1.6981e+02, -1.1565e-01, -1.6958e+02, -8.8278e-02, -1.6972e+02,
         -5.0606e-02, -1.7051e+02, -4.0793e-02, -1.7044e+02, -4.6974e-02,
         -1.7028e+02, -5.1964e-02, -1.7052e+02, -4.6195e-02, -1.6997e+02,
         -5.1488e-02, -1.6970e+02, -3.3158e-02, -1.6926e+02,  2.4980e-02,
         -1.6986e+02,  7.2152e-02, -1.7043e+02,  8.1653e-02, -1.7038e+02,
          8.4323e-02, -1.6942e+02]], grad_fn=<AddmmBackward0>)

In [40]:
predicted_401

tensor([[ 6.3040e-02, -1.7005e+02,  6.7186e-02, -1.6943e+02,  1.1316e-01,
         -1.6972e+02,  1.0122e-01, -1.6944e+02, -2.9859e-02, -1.7122e+02,
         -1.0494e-01, -1.6915e+02, -1.5843e-01, -1.7043e+02, -1.3934e-01,
         -1.6981e+02, -1.1565e-01, -1.6958e+02, -8.8278e-02, -1.6972e+02,
         -5.0607e-02, -1.7051e+02, -4.0796e-02, -1.7044e+02, -4.6976e-02,
         -1.7028e+02, -5.1965e-02, -1.7052e+02, -4.6196e-02, -1.6997e+02,
         -5.1488e-02, -1.6970e+02, -3.3158e-02, -1.6927e+02,  2.4981e-02,
         -1.6986e+02,  7.2154e-02, -1.7043e+02,  8.1653e-02, -1.7038e+02,
          8.4325e-02, -1.6942e+02]], grad_fn=<AddmmBackward0>)

In [41]:
predicted_401_comp

tensor([[ 6.3040e-02, -1.7005e+02,  6.7186e-02, -1.6943e+02,  1.1316e-01,
         -1.6972e+02,  1.0122e-01, -1.6944e+02, -2.9859e-02, -1.7122e+02,
         -1.0494e-01, -1.6915e+02, -1.5843e-01, -1.7043e+02, -1.3934e-01,
         -1.6981e+02, -1.1565e-01, -1.6958e+02, -8.8278e-02, -1.6972e+02,
         -5.0607e-02, -1.7051e+02, -4.0796e-02, -1.7044e+02, -4.6976e-02,
         -1.7028e+02, -5.1965e-02, -1.7052e+02, -4.6196e-02, -1.6997e+02,
         -5.1488e-02, -1.6970e+02, -3.3158e-02, -1.6927e+02,  2.4981e-02,
         -1.6986e+02,  7.2154e-02, -1.7043e+02,  8.1653e-02, -1.7038e+02,
          8.4325e-02, -1.6942e+02]], grad_fn=<AddmmBackward0>)

In [42]:
predicted_test

tensor([[ 6.3040e-02, -1.7005e+02,  6.7186e-02, -1.6943e+02,  1.1316e-01,
         -1.6972e+02,  1.0122e-01, -1.6944e+02, -2.9859e-02, -1.7122e+02,
         -1.0494e-01, -1.6915e+02, -1.5843e-01, -1.7043e+02, -1.3934e-01,
         -1.6981e+02, -1.1565e-01, -1.6958e+02, -8.8278e-02, -1.6972e+02,
         -5.0607e-02, -1.7051e+02, -4.0796e-02, -1.7044e+02, -4.6976e-02,
         -1.7028e+02, -5.1965e-02, -1.7052e+02, -4.6196e-02, -1.6997e+02,
         -5.1488e-02, -1.6970e+02, -3.3158e-02, -1.6927e+02,  2.4981e-02,
         -1.6986e+02,  7.2154e-02, -1.7043e+02,  8.1653e-02, -1.7038e+02,
          8.4325e-02, -1.6942e+02]], grad_fn=<AddmmBackward0>)