In [4]:
import numpy as np

In [12]:
with open("../results/training_in_v05.npy", "rb") as f:
    training_in_loaded = np.load(f)

with open("../results/training_out_v05.npy", "rb") as f:
    training_out_loaded = np.load(f)

In [13]:
training_in_loaded.shape

(6, 2000, 63)

In [14]:
training_in_loaded[2, 1500, 2::3]

array([-26.75906796, -32.67890582, -36.2082705 , -38.24634765,
       -39.29116111, -39.82613847, -40.13273074, -40.3234104 ,
       -40.4449867 , -40.51414939, -40.53674793, -40.51410835,
       -40.4448867 , -40.32322892, -40.13245833, -39.82585088,
       -39.29097877, -38.24644636, -36.20820026, -32.679558  ,
       -26.76039062])

In [15]:
training_out_loaded[0, 1000, 1::2]

array([-3.08421749e-06, -3.08422936e-06, -3.08423465e-06, -3.08424737e-06,
       -3.08424783e-06, -3.08423997e-06, -3.08422727e-06, -3.08421726e-06,
       -3.08421431e-06, -3.08421885e-06, -3.08422916e-06, -3.08424287e-06,
       -3.08425773e-06, -3.08427169e-06, -3.08428279e-06, -3.08428958e-06,
       -3.08429271e-06, -3.08429492e-06, -3.08429840e-06, -3.08429807e-06,
       -3.08429180e-06])

In [ ]:
from workspace.tct.tct_elastic_stress import tct_elastic_generate_u_interface

In [3]:
tct_elastic_generate_u_interface()

0.015707937429397814...............................] 0.1/2000
0.0


0.03141571982779475
-81.44883284559796
0.04712319216572003................................] 2/2000
-162.89686182409787
0.06283019941676303................................] 3/2000
-244.3432830763361
0.07853658655910337................................] 4/2000
-325.78729275901514
0.09424219857704086................................] 5/2000
-407.22808705264083
0.10994688046252551................................] 6/2000
-488.6648621694514
0.12565047721668737................................] 7/2000
-570.0968143613549
0.14135283385136627................................] 8/2000
-651.5231399278575
0.15705379539064146................................] 9/2000
-732.9430352239997
0.17275320687236137................................] 10/2000
-814.3556966682869
0.1884509133496727.................................] 11/2000
-895.760320750615
0.20414675989255002................................] 12/2000
-977.156104040211
0.21984059158932454................................] 13/2000
-1058.5422431935535
0.23553

(array([[-0.00484107,  0.00785388, -0.0042642 , ...,  0.00785409,
          0.00484106,  0.00785407],
        [-0.00484102,  0.00785381, -0.00426416, ...,  0.00785401,
          0.00484101,  0.007854  ],
        [-0.00484093,  0.00785365, -0.00426407, ...,  0.00785386,
          0.00484091,  0.00785384],
        ...,
        [-0.00484093,  0.00785365, -0.00426407, ...,  0.00785386,
          0.00484091,  0.00785384],
        [-0.00484102,  0.00785381, -0.00426416, ...,  0.00785401,
          0.00484101,  0.007854  ],
        [-0.00484107,  0.00785388, -0.0042642 , ...,  0.00785409,
          0.00484106,  0.00785407]]),
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.67334069e+00,  3.39319235e-04, -5.37659029e+01, ...,
          1.67368688e+00,  3.74597487e-04, -5.37685605e+01],
        [ 1.67332417e+00,  3.39315886e-04, -5.37653723e+01, ...,
          1.67367036e+00,  3.74593790e-04, -5.37680298e+

In [6]:
import numpy as np

In [1]:
from misc.plotting import format_vectors_from_flat, create_mesh_animation

In [2]:
from tct.tct_elastic_force_comp import tct_elastic_generate_f_interface, tct_elastic_apply_f_interface

In [3]:
mesh_gen, u_gen, f_interface, bottom_half_nodes = tct_elastic_generate_f_interface()

[██████████████████████████████████████████████████] 6000/6000

Simulation complete


In [4]:
mesh_app, u_app = tct_elastic_apply_f_interface(f_interface)

[██████████████████████████████████████████████████] 6000/6000

Simulation complete


In [7]:
u_gen = np.array(u_gen)
u_app = np.array(u_app)

In [8]:
error = np.zeros(u_gen.shape)
error[:, bottom_half_nodes] = u_gen[:, bottom_half_nodes] - u_app

In [9]:
u_tensor_gen = format_vectors_from_flat(u_gen)
u_tensor_app = format_vectors_from_flat(u_app)
error_tensor = format_vectors_from_flat(error)

In [ ]:
create_mesh_animation(mesh_gen, u_tensor_gen[:, :, 1], u_tensor_gen, name="forces_gen")

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen


In [ ]:
create_mesh_animation(mesh_app, u_tensor_app[:, :, 1], u_tensor_app, name="forces_app")

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen


In [ ]:
create_mesh_animation(mesh_gen, error_tensor[:, :, 1], u_tensor_gen, name="forces_error_timesteps")

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen


In [2]:
from tct.tct_elastic_test import TCTForceExtract

In [3]:
test_sim = TCTForceExtract()
test_sim.time_total = 1e-3
test_sim.run()

[██████████████████████████████████████████████████] 2000/2000



In [9]:
test_sim.postprocess(scalars= "u_y", vectors= "u", name="test")

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
