In [2]:
import numpy as np
import pickle

from sklearn import ensemble
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor

In [3]:
with open("results/training_in_v04.npy", "rb") as f:
    training_in_loaded = np.load(f)

with open("results/training_out_v04.npy", "rb") as f:
    training_out_loaded = np.load(f)

In [4]:
training_in_loaded.shape

(6, 2000, 63)

In [5]:
training_out_loaded.shape

(6, 2000, 42)

In [ ]:
training_in = training_in_loaded.reshape(-1, training_in_loaded.shape[-1])
training_out = training_out_loaded.reshape(-1, training_out_loaded.shape[-1])

In [9]:
training_in.shape

(12000, 63)

In [15]:
training_in_loaded

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.52521331e+01,  1.80385005e+02,  2.26304078e+01, ...,
          1.96848314e+02, -1.51697690e+01,  1.91086168e+02],
        [ 3.05042285e+01,  3.60769565e+02,  4.52607597e+01, ...,
          3.93696142e+02, -3.03395006e+01,  3.82171864e+02],
        ...,
        [ 4.57562487e+01,  5.41153235e+02,  6.78909999e+01, ...,
          5.90542999e+02, -4.55091574e+01,  5.73256618e+02],
        [ 3.05042285e+01,  3.60769565e+02,  4.52607597e+01, ...,
          3.93696142e+02, -3.03395006e+01,  3.82171864e+02],
        [ 1.52521331e+01,  1.80385005e+02,  2.26304078e+01, ...,
          1.96848314e+02, -1.51697690e+01,  1.91086168e+02]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 2.44033973e+01,  2.88615823e+02,  3.62086292e+01, ...,
          3.14957100e+02, -2.42716149e

In [16]:
training_in

array([[    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [   15.25213308,   180.38500515,    22.63040776, ...,
          196.84831383,   -15.16976903,   191.08616787],
       [   30.50422853,   360.76956522,    45.26075969, ...,
          393.69614196,   -30.33950062,   382.17186426],
       ...,
       [ -183.01483406, -2164.4927702 ,  -271.54892366, ...,
        -2362.04085678,   182.02652352, -2292.89917139],
       [ -122.01390346, -1443.04265425,  -181.03857169, ...,
        -1574.74571149,   121.35500809, -1528.64973807],
       [  -61.00815597,  -721.53556945,   -90.52107263, ...,
         -787.38839793,    60.67870178,  -764.33995627]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    training_in, training_out, test_size=0.2, random_state=13
)

params = {
    "n_estimators": 500,
    "max_depth": 4,
    "min_samples_split": 5,
    "learning_rate": 0.01,
    "loss": "squared_error",
}

In [7]:
reg = MultiOutputRegressor(ensemble.GradientBoostingRegressor(**params), n_jobs=-1)
reg.fit(X_train, y_train)

mse = mean_squared_error(y_test, reg.predict(X_test))
print("The mean squared error (MSE) on test set: {:.4f}".format(mse))

The mean squared error (MSE) on test set: 0.0001


In [8]:
with open("model_v3.pkl", "wb") as f:
    pickle.dump(reg, f)

In [24]:
training_out_loaded[0, 500, ::2]

array([-1.09133607e+00, -9.61289850e-01, -8.18904122e-01, -6.78423995e-01,
       -5.48944163e-01, -4.33394322e-01, -3.30952561e-01, -2.39154164e-01,
       -1.55196522e-01, -7.63430617e-02,  2.08944149e-06,  7.63463754e-02,
        1.55197220e-01,  2.39150542e-01,  3.30943326e-01,  4.33379396e-01,
        5.48925483e-01,  6.78404483e-01,  8.18884450e-01,  9.61278376e-01,
        1.09133280e+00])

In [25]:
prediction = reg.predict([training_in_loaded[0, 500, :]])[0]

In [26]:
prediction[::2]

array([-1.08372777e+00, -9.54588179e-01, -8.13195099e-01, -6.73694335e-01,
       -5.45117177e-01, -4.30372896e-01, -3.28645312e-01, -2.37486891e-01,
       -1.54114563e-01, -7.58108329e-02,  2.07688347e-06,  7.58141235e-02,
        1.54115256e-01,  2.37483294e-01,  3.28636141e-01,  4.30358073e-01,
        5.45098626e-01,  6.73674958e-01,  8.13175563e-01,  9.54576785e-01,
        1.08372453e+00])