In [2]:
import numpy as np
import pickle

from sklearn import ensemble
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor

In [3]:
with open("results/training_in_v08.npy", "rb") as f:
    training_in_loaded = np.load(f)

with open("results/training_out_v08.npy", "rb") as f:
    training_out_loaded = np.load(f)

In [4]:
training_in_loaded.shape

(6, 6000, 42)

In [5]:
training_out_loaded.shape

(6, 6000, 42)

In [6]:
training_in = training_in_loaded.reshape(-1, training_in_loaded.shape[-1])
training_out = training_out_loaded.reshape(-1, training_out_loaded.shape[-1])

In [7]:
training_in.shape

(36000, 42)

In [8]:
training_in_loaded

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.69659827e-04, -2.68829846e+01,  1.74496452e-04, ...,
         -3.28308914e+01,  1.87298975e-04, -2.68843134e+01],
        [ 3.39319235e-04, -5.37659029e+01,  3.48992473e-04, ...,
         -6.56617019e+01,  3.74597487e-04, -5.37685605e+01],
        ...,
        [ 5.08977807e-04, -8.06486885e+01,  5.23487633e-04, ...,
         -9.84923503e+01,  5.61895075e-04, -8.06526749e+01],
        [ 3.39319235e-04, -5.37659029e+01,  3.48992473e-04, ...,
         -6.56617019e+01,  3.74597487e-04, -5.37685605e+01],
        [ 1.69659827e-04, -2.68829846e+01,  1.74496452e-04, ...,
         -3.28308914e+01,  1.87298975e-04, -2.68843134e+01]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 2.71455549e-04, -4.30127478e+01,  2.79194144e-04, ...,
         -5.25293926e+01,  2.99678167e

In [9]:
training_in

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.69659827e-04, -2.68829846e+01,  1.74496452e-04, ...,
        -3.28308914e+01,  1.87298975e-04, -2.68843134e+01],
       [ 3.39319235e-04, -5.37659029e+01,  3.48992473e-04, ...,
        -6.56617019e+01,  3.74597487e-04, -5.37685605e+01],
       ...,
       [-2.03579820e-03,  3.22576845e+02, -2.09383428e-03, ...,
         3.93947530e+02, -2.24745553e-03,  3.22592790e+02],
       [-1.35724345e-03,  2.15058305e+02, -1.39593545e-03, ...,
         2.62640327e+02, -1.49835298e-03,  2.15068935e+02],
       [-6.78635122e-04,  1.07531275e+02, -6.97981501e-04, ...,
         1.31322756e+02, -7.49191277e-04,  1.07536590e+02]])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    training_in, training_out, test_size=0.2, random_state=13
)

params = {
    "n_estimators": 500,
    "max_depth": 4,
    "min_samples_split": 5,
    "learning_rate": 0.01,
    "loss": "squared_error",
}

In [11]:
reg = MultiOutputRegressor(ensemble.GradientBoostingRegressor(**params), n_jobs=-1)
reg.fit(X_train, y_train)

mse = mean_squared_error(y_test, reg.predict(X_test))
print("The mean squared error (MSE) on test set: {:.4f}".format(mse))

The mean squared error (MSE) on test set: 0.0001


In [12]:
with open("model_v08.pkl", "wb") as f:
    pickle.dump(reg, f)

In [13]:
training_out_loaded[0, 500, ::2]

array([-1.09133607e+00, -9.61289850e-01, -8.18904122e-01, -6.78423995e-01,
       -5.48944163e-01, -4.33394322e-01, -3.30952561e-01, -2.39154164e-01,
       -1.55196522e-01, -7.63430617e-02,  2.08944149e-06,  7.63463754e-02,
        1.55197220e-01,  2.39150542e-01,  3.30943326e-01,  4.33379396e-01,
        5.48925483e-01,  6.78404483e-01,  8.18884450e-01,  9.61278376e-01,
        1.09133280e+00])

In [14]:
prediction = reg.predict([training_in_loaded[0, 500, :]])[0]

In [15]:
prediction[::2]

array([-1.08376632e+00, -9.54622137e-01, -8.13224027e-01, -6.73718301e-01,
       -5.45136569e-01, -4.30388206e-01, -3.28657003e-01, -2.37495340e-01,
       -1.54120046e-01, -7.58135298e-02,  2.07679936e-06,  7.58168206e-02,
        1.54120739e-01,  2.37491743e-01,  3.28647832e-01,  4.30373383e-01,
        5.45118018e-01,  6.73698924e-01,  8.13204491e-01,  9.54610743e-01,
        1.08376308e+00])