In [2]:
import numpy as np
import pickle

from sklearn import ensemble
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor

In [3]:
with open("results/training_in_v04.npy", "rb") as f:
    training_in_loaded = np.load(f)

with open("results/training_out_v04.npy", "rb") as f:
    training_out_loaded = np.load(f)

In [4]:
training_in_loaded.shape

(6, 2000, 63)

In [5]:
training_out_loaded.shape

(6, 2000, 42)

In [6]:
training_in = training_in_loaded.reshape(-1, training_in_loaded.shape[-1])
training_out = training_out_loaded.reshape(-1, training_out_loaded.shape[-1])

In [7]:
training_in.shape

(12000, 63)

In [8]:
training_in_loaded

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 8.36671376e-01,  1.69659827e-04, -2.68829846e+01, ...,
          8.36844472e-01,  1.87298975e-04, -2.68843134e+01],
        [ 1.67334069e+00,  3.39319235e-04, -5.37659029e+01, ...,
          1.67368688e+00,  3.74597487e-04, -5.37685605e+01],
        ...,
        [ 2.51000587e+00,  5.08977807e-04, -8.06486886e+01, ...,
          2.51052516e+00,  5.61895076e-04, -8.06526749e+01],
        [ 1.67334069e+00,  3.39319236e-04, -5.37659029e+01, ...,
          1.67368688e+00,  3.74597487e-04, -5.37685605e+01],
        [ 8.36671376e-01,  1.69659827e-04, -2.68829846e+01, ...,
          8.36844472e-01,  1.87298975e-04, -2.68843134e+01]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.33867334e+00,  2.71455549e-04, -4.30127478e+01, ...,
          1.33895030e+00,  2.99678167e

In [9]:
training_in

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 8.36671376e-01,  1.69659827e-04, -2.68829846e+01, ...,
         8.36844472e-01,  1.87298975e-04, -2.68843134e+01],
       [ 1.67334069e+00,  3.39319235e-04, -5.37659029e+01, ...,
         1.67368688e+00,  3.74597487e-04, -5.37685605e+01],
       ...,
       [-1.00394661e+01, -2.03579820e-03,  3.22576845e+02, ...,
        -1.00415431e+01, -2.24745553e-03,  3.22592790e+02],
       [-6.69319760e+00, -1.35724345e-03,  2.15058305e+02, ...,
        -6.69458233e+00, -1.49835298e-03,  2.15068935e+02],
       [-3.34666486e+00, -6.78635122e-04,  1.07531275e+02, ...,
        -3.34735724e+00, -7.49191277e-04,  1.07536590e+02]])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    training_in, training_out, test_size=0.2, random_state=13
)

params = {
    "n_estimators": 500,
    "max_depth": 4,
    "min_samples_split": 5,
    "learning_rate": 0.01,
    "loss": "squared_error",
}

In [11]:
reg = MultiOutputRegressor(ensemble.GradientBoostingRegressor(**params), n_jobs=-1)
reg.fit(X_train, y_train)

mse = mean_squared_error(y_test, reg.predict(X_test))
print("The mean squared error (MSE) on test set: {:.4f}".format(mse))

The mean squared error (MSE) on test set: 0.0000


In [12]:
with open("model_v04.pkl", "wb") as f:
    pickle.dump(reg, f)

In [13]:
training_out_loaded[0, 500, ::2]

array([-1.71023528e-03, -1.50643955e-03, -1.28330655e-03, -1.06315981e-03,
       -8.60251670e-04, -6.79173246e-04, -5.18636525e-04, -3.74779045e-04,
       -2.43208829e-04, -1.19637389e-04,  3.27436880e-09,  1.19642582e-04,
        2.43209923e-04,  3.74773369e-04,  5.18622052e-04,  6.79149855e-04,
        8.60222395e-04,  1.06312924e-03,  1.28327572e-03,  1.50642157e-03,
        1.71023016e-03])

In [14]:
prediction = reg.predict([training_in_loaded[0, 500, :]])[0]

In [15]:
prediction[::2]

array([-1.88840044e-05, -1.66337413e-05, -1.41699606e-05, -1.17391536e-05,
       -9.49869096e-06, -7.49926678e-06, -5.72665912e-06, -4.13821961e-06,
       -2.68545309e-06, -1.32100712e-06, -1.82999156e-10,  1.32106446e-06,
        2.68546517e-06,  4.13815693e-06,  5.72649931e-06,  7.49900850e-06,
        9.49836772e-06,  1.17388160e-05,  1.41696202e-05,  1.66335428e-05,
        1.88839480e-05])